import { getEnv } from '@cm/api-common';

export const authConfig = () => ({
  JWT_ACCESS_TOKEN_SECRET: getEnv('JWT_ACCESS_TOKEN_SECRET') || 'JWT_ACCESS_TOKEN_SECRET',
  JWT_ACCESS_TOKEN_EXPIRATION_TIME: getEnv('JWT_ACCESS_TOKEN_EXPIRATION_TIME') || '300',
  JWT_REFRESH_TOKEN_SECRET:
    getEnv('JWT_REFRESH_TOKEN_SECRET') || 'JWT_REFRESH_TOKEN_SECRET',
  JWT_REFRESH_TOKEN_EXPIRATION_TIME:
    getEnv('JWT_REFRESH_TOKEN_EXPIRATION_TIME') || '10080', //1week
  JWT_REFRESH_TOKEN_HASH_PEPPER:
    getEnv('JWT_REFRESH_TOKEN_HASH_PEPPER') || 'JWT_REFRESH_TOKEN_HASH_PEPPER',
  PW_HASH_PEPPER: getEnv('PW_HASH_PEPPER') || 'PW_HASH_PEPPER',
});
