#version: '2.4'
services:
#  redis:
#    image: redis:alpine
#    container_name: redis
#    restart: on-failure
#    # command: redis-server --requirepass ${REDIS_PASSWORD}
#    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
#      - REDIS_REPLICATION_MODE=master
#    ports:
#      - ${REDIS_PORT}:6379
#    volumes:
#      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
#      - ./data:/data
#
#  redis-commander:
#    image: rediscommander/redis-commander:latest
#    container_name: redis-commander
#    restart: on-failure
#    environment:
#      - REDIS_HOSTS=local:idss-redis:${REDIS_PORT}
#      - SERVICE_USER=redis
#      - HOME=/redis-commander
#    ports:
#      - ${REDIS_COMMANDER_PORT}:8081

  cm-arena:
    image: node:alpine
    working_dir: /app
    volumes:
      - ./arena:/app
    environment:
      - REDIS_HOSTS=local:cm-redis:6379
      - SERVICE_USER=redis
    ports:
      - 4735:4735
    command: sh -c "npm ci --quiet && node main.js"

#  arena:
#    image: node:latest
#    container_name: arena
#    restart: on-failure
#    working_dir: /app
#    volumes:
#      - ./arena:/app
#    environment:
#      - REDIS_HOSTS=local:idss-redis:${REDIS_PORT}
#      - SERVICE_USER=redis
#    ports:
#      - ${ARENA_PORT}:${ARENA_PORT}
#    command: sh -c "npm install --quiet && node main.js"
